server:
  port: ${PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: interview_manager

  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:interview_manager}?currentSchema=${DB_SCHEMA:public}'
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL:10}
      minimum-idle: ${HIKARI_MAX_POOL:10}
      driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog-master.yaml

  jackson:
    default-property-inclusion: non_null

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info

message:
  error: 'Извините, что-то пошло не так, попробуйте позже...'
  not-found-command: 'Извините, мне не доступна такая команда...'

manager-bot:
  token: ${MANAGER_BOT_TOKEN:}
  name: ${MANAGER_BOT_NAME:InterviewManagerBot}
